### ISSUE TITLE
Doesn't work on React v0.12.0

### ISSUE THREAD

**Issue by mizchi** [snd/react-kup#1]
```
Uncaught Error: Invariant Violation: ReactCompositeComponent.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object. 
```

**Comment by snd** [comment]
hey mizchi,

sorry for taking so long to react !

i just tried to reproduce the problem with react 0.12.0 and 0.12.1.
all tests pass - i could not reproduce it and have no idea what to fix.

could you post a minimal code example that produces your problem.
i'll be happy to fix it then !

best
max

**Comment by e-jigsaw** [comment]
Hi all.

I have same error has occur like this: `Uncaught Error: Invariant Violation: ReactCompositeComponent.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.`.

Code is

```
React = require 'react/addons'
kup = require 'react-kup'

HelloMessage = React.createClass
  render: -> kup (k)=> k.div "Hello #{@props.name}"

init = ->
  mountNode = document.getElementById 'user'
  component = new HelloMessage
    name: 'John'

  React.renderComponent component, mountNode
```

and browserified. However, I was wrong to be carefully read `README`.

`kup = require 'react-kup'` is correctly was `kup = require('react-kup')(React)`. And it is worked with react@0.12.2.

I thought the same mistake.

Thanks

**Comment by snd** [comment]
thanks for the effort !

i'll make that clearer in the readme soon.
