### ISSUE TITLE
react versioning

### ISSUE THREAD

**Issue by wiber** [snd/react-kup#5]
Hi,

This works like a dream seems to force me to use an older react. I'll attempt to fix it.

Cheers

**Comment by wiber** [comment]
```
npm list react
react-kup@0.5.2 /Users/zing/Documents/react-kup
└── react@15.0.1 
```

npm test gives:

```
# tests 25
# pass  21
# fail  4
```

Care to have a look? React 0.14.8 Ran ok.

**Comment by snd** [comment]
@sh was so kind as to make react-kup work with react 15 👍 

on top of that i've made react and react-dom peerDependencies so you can now choose your version.

use version 1.0.0 which i've just published

**Comment by wiber** [comment]
Pure awesome. Thanks and cheers.
